from .watson_conversation import watson_conversation
from .watson_speech_to_text import watson_speech_to_text
from .watson_text_to_speech import watson_text_to_speech
from .watson_tone_analizer import watson_tone_analizer
from .sphinx_speech_to_text import sphinx_speech_to_text
from .wit_speech_to_text import wit_speech_to_text
